BEGIN;

CREATE TABLE "role" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" TEXT NOT NULL                                    
);

CREATE TABLE "user" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "password" TEXT NOT NULL,                               
    "mail" TEXT UNIQUE NOT NULL,                           
    "name" VARCHAR(50),                             
    "age" SMALLINT,                                  
    "available" BOOLEAN,                           
    "description" TEXT,                           
    "portfolio_url" TEXT,                                   
    "profile_mail" TEXT,                          
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,                     
    "updated_at" TIMESTAMP,                                     
    "role" INT NOT NULL DEFAULT 2, -- user                                   
    CONSTRAINT fk_role FOREIGN KEY ("role") REFERENCES "role"("id")
);

CREATE TABLE "job" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" VARCHAR(50) NOT NULL                                    
);

CREATE TABLE "language" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" VARCHAR(50) NOT NULL                                    
);


CREATE TABLE "remuneration" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "type" VARCHAR(50) NOT NULL                                    
);

CREATE TABLE "user_job" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "job_id" INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE,
    CONSTRAINT fk_job FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE
);

CREATE TABLE "user_language" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "language_id" INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE,
    CONSTRAINT fk_language FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE
);

CREATE TABLE "user_remuneration" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "remuneration_id" INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE,
    CONSTRAINT fk_remuneration FOREIGN KEY ("remuneration_id") REFERENCES "remuneration"("id") ON DELETE CASCADE
);

COMMIT;