BEGIN;

CREATE TABLE "role" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" TEXT NOT NULL                                    
);

CREATE TABLE "utilisateur" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "password" TEXT NOT NULL,                               
    "mail" TEXT UNIQUE NOT NULL,                           
    "name" VARCHAR(50) NOT NULL,                             
    "age" SMALLINT NOT NULL,                                  
    "available" BOOLEAN NOT NULL,                           
    "description" TEXT NOT NULL,                           
    "portfolio_url" TEXT,                                   
    "profile_mail" TEXT NOT NULL,                          
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,                     
    "updated_at" TIMESTAMP,                                     
    "role" INT NOT NULL,                                    
    CONSTRAINT fk_role FOREIGN KEY ("role") REFERENCES "role"("id")
);

CREATE TABLE "job" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" VARCHAR(50) NOT NULL                                    
);

CREATE TABLE "language" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "name" VARCHAR(50) NOT NULL                                    
);


CREATE TABLE "remuneration" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    "type" VARCHAR(50) NOT NULL                                    
);

CREATE TABLE "utilisateur_job" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "utilisateur_id" INT NOT NULL,
    "job_id" INT NOT NULL,
    CONSTRAINT fk_utilisateur FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur"("id") ON DELETE CASCADE,
    CONSTRAINT fk_job FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE
);

CREATE TABLE "utilisateur_language" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "utilisateur_id" INT NOT NULL,
    "language_id" INT NOT NULL,
    CONSTRAINT fk_utilisateur FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur"("id") ON DELETE CASCADE,
    CONSTRAINT fk_language FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE
);

CREATE TABLE "utilisateur_remuneration" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "utilisateur_id" INT NOT NULL,
    "remuneration_id" INT NOT NULL,
    CONSTRAINT fk_utilisateur FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur"("id") ON DELETE CASCADE,
    CONSTRAINT fk_remuneration FOREIGN KEY ("remuneration_id") REFERENCES "remuneration"("id") ON DELETE CASCADE
);

COMMIT;